from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.energycast_core import (  # noqa: E402
    LOCAL_TZ,
    LOCAL_TIMESTAMP,
    ScenarioSettings,
    build_forecast_bundle,
    forecast_future_scenario,
    forecast_summary,
    format_metric_table,
)
from src.energycast_plots import make_forecast_output_figure, make_input_context_figure  # noqa: E402


st.set_page_config(
    page_title="EnergyCast Scenario Forecast",
    layout="wide",
)


@st.cache_resource(show_spinner="Loading the trained forecast pipeline...")
def load_dashboard_bundle(root: str):
    return build_forecast_bundle(root)


def metric_value(value: float, suffix: str = "", digits: int = 1) -> str:
    if pd.isna(value):
        return "n/a"
    return f"{value:,.{digits}f}{suffix}"


def format_timestamp(value) -> str:
    if pd.isna(value):
        return "n/a"
    return pd.Timestamp(value).strftime("%Y-%m-%d %H:%M")


try:
    bundle = load_dashboard_bundle(str(ROOT))
except Exception as exc:  # pragma: no cover - visible app fallback
    st.error("The forecast data could not be prepared.")
    st.exception(exc)
    st.stop()


st.sidebar.title("Forecast controls")
st.sidebar.caption("Generate future Germany load scenarios from the trained EnergyCast model.")

min_date = pd.Timestamp("2020-01-01").date()
max_date = pd.Timestamp("2030-12-31").date()
today = pd.Timestamp.now(tz=LOCAL_TZ).date()
default_date = min(max(today, min_date), max_date)
start_date = st.sidebar.date_input(
    "Forecast start date",
    value=default_date,
    min_value=min_date,
    max_value=max_date,
)
start_hour = st.sidebar.slider("Forecast start hour", 0, 23, 0, step=1)
horizon_label = st.sidebar.radio(
    "Forecast horizon",
    ["Next 24 hours", "Next 48 hours", "Next 7 days", "Next 30 days"],
    index=2,
)
horizon_hours = {
    "Next 24 hours": 24,
    "Next 48 hours": 48,
    "Next 7 days": 168,
    "Next 30 days": 720,
}[horizon_label]
demand_growth = st.sidebar.slider("Demand growth per year (%)", -3.0, 5.0, 0.5, step=0.1)
temperature_shift = st.sidebar.slider("Temperature shift (C)", -5.0, 5.0, 0.0, step=0.5)
renewable_scale = st.sidebar.slider("Renewable generation scale (%)", 50, 150, 100, step=5)
show_inputs = st.sidebar.toggle("Show input columns in table", value=False)

settings = ScenarioSettings(
    demand_growth_pct_per_year=demand_growth,
    temperature_shift_c=temperature_shift,
    renewable_generation_scale_pct=float(renewable_scale),
)

try:
    window = forecast_future_scenario(
        bundle.model_data,
        bundle.selected_estimator,
        start_date=start_date,
        start_hour=start_hour,
        horizon_hours=horizon_hours,
        settings=settings,
    )
except Exception as exc:  # pragma: no cover - visible app fallback
    st.error("The future scenario forecast could not be generated.")
    st.exception(exc)
    st.stop()

window = window.sort_values(LOCAL_TIMESTAMP).copy()

if window.empty:
    st.warning("No forecast rows are available for that scenario.")
    st.stop()

summary = forecast_summary(window)

st.title("EnergyCast Scenario Forecast")
st.caption(
    "Hourly electricity-load forecasts for Germany, generated by the trained EnergyCast model from future scenario inputs."
)

forecast_tab, inputs_tab, assumptions_tab = st.tabs(["Scenario Forecast", "Generated Inputs", "Assumptions"])

with forecast_tab:
    st.subheader("Hourly load forecast")
    st.write(
        f"Forecast window: {format_timestamp(window[LOCAL_TIMESTAMP].iloc[0])} to "
        f"{format_timestamp(window[LOCAL_TIMESTAMP].iloc[-1])}."
    )

    kpi1, kpi2, kpi3, kpi4 = st.columns(4)
    with kpi1:
        st.metric("Peak forecast", metric_value(summary["peak_forecast_MW"], " MW"))
    with kpi2:
        st.metric("Peak hour", format_timestamp(summary["peak_timestamp"]))
    with kpi3:
        st.metric("Average forecast", metric_value(summary["average_forecast_MW"], " MW"))
    with kpi4:
        st.metric("Forecasted energy", metric_value(summary["forecasted_energy_GWh"], " GWh", 2))

    st.plotly_chart(make_forecast_output_figure(window), width="stretch")

    forecast_table_cols = [LOCAL_TIMESTAMP, "prediction_MW", "scenario_baseline_load_MW", "scenario_demand_factor"]
    if show_inputs:
        forecast_table_cols.extend(
            [
                "load_lag_1h",
                "load_lag_24h",
                "load_lag_168h",
                "DE_temperature_lag1h",
                "DE_solar_generation_actual_lag1h",
                "DE_wind_generation_actual_lag1h",
            ]
        )
    forecast_table = window[[col for col in forecast_table_cols if col in window.columns]].rename(
        columns={
            LOCAL_TIMESTAMP: "forecast_timestamp",
            "prediction_MW": "forecast_load_MW",
            "scenario_baseline_load_MW": "seasonal_load_baseline_MW",
            "scenario_demand_factor": "demand_factor",
        }
    )
    st.dataframe(format_metric_table(forecast_table), hide_index=True, width="stretch")

with inputs_tab:
    st.subheader("Generated forecast inputs")
    st.write(
        "The model receives calendar features, generated weather and renewable inputs, and recursive load lags. "
        "Future actual load is not used."
    )
    st.plotly_chart(make_input_context_figure(window), width="stretch")

    first_row = window.iloc[0]
    context = pd.DataFrame(
        [
            {"input": "Demand growth factor", "value": f"{first_row['scenario_demand_factor']:,.3f}"},
            {"input": "Temperature shift", "value": f"{temperature_shift:,.1f} C"},
            {"input": "Renewable generation scale", "value": f"{renewable_scale:,.0f}%"},
            {"input": "Previous hour load input", "value": f"{first_row['load_lag_1h']:,.1f} MW"},
            {"input": "Same hour previous day input", "value": f"{first_row['load_lag_24h']:,.1f} MW"},
            {"input": "Same hour previous week input", "value": f"{first_row['load_lag_168h']:,.1f} MW"},
            {"input": "Temperature one hour ago input", "value": f"{first_row['DE_temperature_lag1h']:,.1f} C"},
            {"input": "Solar generation one hour ago input", "value": f"{first_row['DE_solar_generation_actual_lag1h']:,.1f} MW"},
            {"input": "Wind generation one hour ago input", "value": f"{first_row['DE_wind_generation_actual_lag1h']:,.1f} MW"},
        ]
    )
    st.dataframe(context, hide_index=True, width="stretch")

with assumptions_tab:
    st.subheader("Forecast scope")
    st.write(
        "EnergyCast was trained on 2015-2018 Germany hourly data and checked on the unseen 2019 holdout year. "
        "For 2020+ forecasts, OPSD actual target values are not available inside the project, so this app builds "
        "future feature rows from historical seasonal patterns and the selected scenario controls before calling the model."
    )
    st.write(
        "The forecast is therefore a scenario forecast, not a measured future truth. Real production forecasting would replace "
        "these generated inputs with live load history plus weather and renewable forecasts available at prediction time."
    )
